@SalesService.API_HostAddress = http://localhost:5186

GET {{SalesService.API_HostAddress}}/todos/
Accept: application/json

###

GET {{SalesService.API_HostAddress}}/todos/1
Accept: application/json

###
